apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: "$(cat user.csr | base64 -w 0)"
  signerName: example.com/serving
  usages:
  - digital signature
  - key encipherment
  - server auth
