apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: my-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: my-containers
          image: nginx
          ports:
            - containerPort: 80
