apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydeploy
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: mypod
      labels:
        app: web
    spec:
      containers:
        - name: mycontainer
          image: nginx

