apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 20
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: mypod
      labels:
        app: frontend
    spec:
      containers:
        - name: webcontainer
          image: princenarula00/gymwork
          ports:
            - containerPort: 80
        - name: web
          image: nginx
