apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
spec:
  containers:
  - name: main-container
    image: busybox
    command: ['sh', '-c', 'echo "Main container started"; sleep 3600']
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo "Initializing"; sleep 25']
