apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
    - name: webapp
      image: nginx
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'echo "Initializing"; sleep 30']
