apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
    - name: firstcontainer
      image: httpd
    - name: secondcontainer
      image: ubuntu
      command: ["sleep"]
      args: ["10"]
