apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: dbpod
      labels:
        app: backend
    spec:
      containers:
        - name: dbcontainer
          image: mysql
          envFrom:
            - secretRef:
                name: dbsecret
          envFrom:
            - configMapRef:
                name: dbconfig
