---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployweb
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: mypodweb
      labels:
        app: web
    spec:
      containers:
        - name: mycontainerweb
          image: nginx
          volumeMounts:
            - name: myvol
              mountPath: /usr/share/nginx/html
      volumes:
        - name: myvol
          persistentVolumeClaim:
            claimName: mypvc
---
apiVersion: v1
kind: Service
metadata:
  name: nodeportsvc
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080
