apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prince
  name: admin-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
