apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rolebinding
  namespace: prince
subjects:
- kind: User
  name: prince
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin-role 
  apiGroup: rbac.authorization.k8s.io
